### ISSUE TITLE
[Feature request] Libretro port?

### ISSUE THREAD

**Issue by Cee123** [djipi/Virtual-Jaguar-Rx#25]
Hi guys, is it possible to make a libretro port of this in future? This needs to be available for other platforms such as Linux and Android. Unfortunately the original virtual jaguar is not very good and is full of bugs and glitches.

I've made a list of games on the libretro github that have issues in the original virtual jaguar.
https://github.com/libretro/virtualjaguar-libretro/issues/38

Just a bunch of the issues I've noticed. Not sure if many of them are still in the RX version. I'll do some testing a bit later.

**Comment by djipi** [comment]
Hi,

Virtualjaguar Rx is dedicated to add a debugger in the emulator, and not intended to improve the game support. Using the debugger may help to understand potential compatibilities issues between the emulator and games. I have fixed some stability in the emulator when in alpine mode, otherwise no improvements in the game compatibility has been made.

Sadly, to port the Rx version to libreto won't help the game compatibility.

**Comment by Cee123** [comment]
> 
> 
> Hi,
> 
> Virtualjaguar Rx is dedicated to add a debugger in the emulator, and not intended to improve the game support. Using the debugger may help to understand potential compatibilities issues between the emulator and games. I have fixed some stability in the emulator when in alpine mode, otherwise no improvements in the game compatibility has been made.
> 
> Sadly, to port the Rx version to libreto won't help the game compatibility.

Oh I see. Interesting, thanks for the info. Well that's disappointing. Hopefully though the debugger can tell us a lot about this emulator, how it functions, the causes of several bugs and glitches in its compatibility.
